// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © iFlyTheMoon

//@version=5

library("MoreCandleInfo", overlay=true)

export type MoreCandleInfo
	float spread
    float body_low
    float body_high
    float body   
    float abs_body
	float shadow_low
	float shadow_high
    bool  is_bullish
    bool  is_bearish

export init() =>
	body_low = math.min(open, close)
	body_high = math.max(open, close)
    MoreCandleInfo.new(spread=high - low,
                       body_low=body_low,
					   body_high=body_high,
					   body=close - open,
					   abs_body=math.abs(close - open),
					   shadow_low=body_low - low,
					   shadow_high=high - body_high,
					   is_bullish=close > open,
					   is_bearish=close < open)

export arrayify(series MoreCandleInfo id, int n_back) =>
	array<MoreCandleInfo> result = array.new<MoreCandleInfo>(n_back + 1)
	for i = 0 to n_back
		array.set(result, i, id[i])
	result

