// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © iFlyTheMoon

//@version=5

library("MoreCandleInfo", overlay=true)

spread     = high - low
body_low   = math.min(open, close)
body_high  = math.max(open, close)
body       = close - open
abs_body   = math.abs(body)
is_bullish = close > open
is_bearish = close < open

export spread() => spread
export spread(int n_back) => spread[n_back]
export body_low() => body_low
export body_low(int n_back) => body_low[n_back]
export body_high() => body_high
export body_high(int n_back) => body_high[n_back]
export body() => body
export body(int n_back) => body[n_back]
export abs_body() => abs_body
export abs_body(int n_back) => abs_body[n_back]
export is_bullish() => is_bullish
export is_bullish(int n_back) => is_bullish[n_back]
export is_bearish() => is_bearish
export is_bearish(int n_back) => is_bearish[n_back]

